services:
  dynamic-reverse-proxy:
    image: dynamic-reverse-proxy  
    ports:
      - "8000:8000" 
      - "80:80"     
    network_mode: bridge
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  
    